import {
  appleLogo,
  bookShelfImage,
  cameraIcon,
  cellPhoneIcon,
  chairImage,
  computerIcon,
  controllerImage,
  coolerImage,
  gamepadIcon,
  gucciCoatImage,
  gucciSavoyImage,
  headphoneIcon,
  iphoneImage,
  keyboardImage,
  monitorImage,
  smartWatchIcon,
} from "./constants";

export const categories = [
  "woman's fashion",
  "men's fashion",
  "electronics",
  "home & lifestyle",
  "medicine",
  "sports & outdoor",
  "baby's & toys",
  "groceries & pets",
  "health & beauty",
];

export const sliderImages = [
  {
    productId: "1",
    title: "iPhone 14 Series",
    body: "Up to 10% off Voucher",
    image: iphoneImage,
    logo: appleLogo,
  },
  {
    productId: "2",
    title: "iBag 7 Series",
    body: "Up to 5% off Voucher",
    image: gucciSavoyImage,
    logo: appleLogo,
  },
  {
    productId: "3",
    title: "iCoat 15 Series",
    body: "Up to 20% off Voucher",
    image: gucciCoatImage,
    logo: appleLogo,
  },
  {
    productId: "4",
    title: "iCooler 12 Series",
    body: "Up to 15% off Voucher",
    image: coolerImage,
    logo: appleLogo,
  },
  {
    productId: "5",
    title: "iShelf 11 Series",
    body: "Up to 30% off Voucher",
    image: bookShelfImage,
    logo: appleLogo,
  },
];

export const flashProducts = [
  {
    id: 0,
    title: "HAVIT HV-G92 Gamepad",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 160,
    discountPrice: 120,
    ratings: 88,
    averageRating: 5,
    img: controllerImage,
    quantity: 10,
  },
  {
    id: 1,
    title: "AK-900 Wired Keyboard",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 1160,
    discountPrice: 960,
    ratings: 75,
    averageRating: 4,
    img: keyboardImage,
    quantity: 1,
  },
  {
    id: 2,
    title: "IPS LCD Gaming Monitor",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 400,
    discountPrice: 370,
    ratings: 99,
    averageRating: 5,
    img: monitorImage,
    quantity: 1,
  },
  {
    id: 3,
    title: "S-Series Comfort Chair ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 400,
    discountPrice: 375,
    ratings: 99,
    averageRating: 4.5,
    img: chairImage,
    quantity: 1,
  },
  {
    id: 4,
    title: "S-Series Comfort Chair ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 400,
    discountPrice: 375,
    ratings: 99,
    averageRating: 4.5,
    img: chairImage,
    quantity: 1,
  },
  {
    id: 5,
    title: "S-Series Comfort Chair ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 400,
    discountPrice: 375,
    ratings: 99,
    averageRating: 4.5,
    img: chairImage,
    quantity: 1,
  },
  {
    id: 6,
    title: "S-Series Comfort Chair ",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut atque, eum dolorum illum dolores, tempore voluptas earum vero voluptatibus eveniet quo",
    price: 400,
    discountPrice: 375,
    ratings: 99,
    averageRating: 4.5,
    img: chairImage,
    quantity: 1,
  },
];

export const bestProducts = [
  {
    id: 1,
    title: "The north coat",
    price: 360,
    discountPrice: 260,
    ratings: 65,
    averageRating: 5,
    img: gucciCoatImage,
  },
  {
    id: 2,
    title: "Gucci duffle bag",
    price: 1160,
    discountPrice: 960,
    ratings: 65,
    averageRating: 4.5,
    img: gucciSavoyImage,
  },
  {
    id: 3,
    title: "RGB liquid CPU Cooler",
    price: 170,
    discountPrice: 160,
    ratings: 65,
    averageRating: 4.5,
    img: coolerImage,
  },
  {
    id: 4,
    title: "Small BookShelf",
    price: 360,
    ratings: 65,
    averageRating: 5,
    img: bookShelfImage,
  },
  {
    id: 5,
    title: "Small BookShelf",
    price: 360,
    ratings: 65,
    averageRating: 5,
    img: bookShelfImage,
  },
  {
    id: 6,
    title: "The north coat",
    price: 360,
    discountPrice: 260,
    ratings: 65,
    averageRating: 5,
    img: bookShelfImage,
  },
  {
    id: 7,
    title: "Gucci duffle bag",
    price: 1160,
    discountPrice: 960,
    ratings: 65,
    averageRating: 4.5,
    img: gucciSavoyImage,
  },
  {
    id: 8,
    title: "RGB liquid CPU Cooler",
    price: 170,
    discountPrice: 160,
    ratings: 65,
    averageRating: 4.5,
    img: coolerImage,
  },
  {
    id: 9,
    title: "Small BookShelf",
    price: 360,
    ratings: 65,
    averageRating: 5,
    img: bookShelfImage,
  },
  {
    id: 10,
    title: "Small BookShelf",
    price: 360,
    ratings: 65,
    averageRating: 5,
    img: bookShelfImage,
  },
];

export const categoryItems = [
  {
    id: 1,
    title: "phones",
    img: cellPhoneIcon,
  },
  {
    id: 2,
    title: "computers",
    img: computerIcon,
  },
  {
    id: 3,
    title: "smartWatch",
    img: smartWatchIcon,
  },
  {
    id: 4,
    title: "camera",
    img: cameraIcon,
  },
  {
    id: 5,
    title: "headPhones",
    img: headphoneIcon,
  },
  {
    id: 6,
    title: "games",
    img: gamepadIcon,
  },
  {
    id: 7,
    title: "games",
    img: gamepadIcon,
  },
];
